### ISSUE TITLE
Please specify the code license

### ISSUE THREAD

**Issue by simnalamburt** [frientrip/jekyll-theme#1]
#### Why should I specify the license?
I want to use this project, but the license of this code is currently unspecified. By the [Berne Convetion] and [WIPO Copyright Treaty], software published without a license does not grant people to benefit or redistribute in [most countries]. If you agree with the [Free Software movement], please specify the license of this project.

#### Which one?
1. If you prefer a GPL-family license, **GNU Affero General Public License** is the perfect choice for this project since it is about server-side codes.
2. If you prefer a permissive license, I think **Apache-2.0/MIT Dual License** is most suitable for this project.

#### Why Apache-2.0/MIT?
The MIT license requires reproducing countless copies of the same copyright header with different names in the copyright field, for every MIT library in use. The Apache license does not have this drawback. However, this is not the primary motivation for me to do this. The Apache license also gives protection from patent trolls and an explicit contribution licensing clause. However, the Apache license is incompatible with GPLv2. This is why Rust is dual-licensed as MIT/Apache (the "primary" license being Apache, MIT only for GPLv2 compat), and doing so would be wise for this project.

Some ask, "Does this really apply to binary redistributions? Does MIT really require reproducing the whole thing?" I'm not a lawyer and I can't give any legal advice, but some Google Android apps include open source attributions using this interpretation. Others also agree with it.

But again, the copyright notice redistribution is not the primary motivation for the dual-licensing. It's stronger protections to licensees and better interoperation with the wider ecosystem.

#### What should I do to specify license?
You should add `LICENSE` file properly and add some notes or comments about it to the existing codes or `README.md`. If this process if hard for you, just tell me the name of your desired license. I'll make a pull request enabling it for you. :smile:

###### Reference
- http://choosealicense.com/

[Berne Convetion]: https://en.wikipedia.org/wiki/Berne_Convention
[WIPO Copyright Treaty]: https://en.wikipedia.org/wiki/WIPO_Copyright_Treaty
[most countries]: https://en.wikipedia.org/wiki/World_Intellectual_Property_Organization
[Free Software movement]: https://www.gnu.org/philosophy/free-software-intro.html

**Comment by saystone** [comment]
@simnalamburt 이 리파지토리가 관리가 되질 않아서 신경을 못쓰고 있었네요. 라이센스 명시해 두었으니 참고해주세요. 감사합니다. :)
https://github.com/frientrip/jekyll-theme/commit/0c0ada39b01238a08cf4aaf29576cc3282977048
